# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocyclo
    - gosec
    - stylecheck
    - revive

  disable:
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

  gosec:
    excludes:
      - G404 # Use of weak random number generator - acceptable for test data

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "should have comment"
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0